<?
$arClasses = array(
	"CBPActivity" => "classes/general/activity.php",
	"CBPActivityCondition" => "classes/general/activitycondition.php",
	"CBPCompositeActivity" => "classes/general/compositeactivity.php",
	"CBPActivityExecutionStatus" => "classes/general/constants.php",
	"CBPActivityExecutionResult" => "classes/general/constants.php",
	"CBPWorkflowStatus" => "classes/general/constants.php",
	"CBPActivityExecutorOperationType" => "classes/general/constants.php",
	"CBPDocumentEventType" => "classes/general/constants.php",
	"CBPCanUserOperateOperation" => "classes/general/constants.php",
	"CBPSetPermissionsMode" => "classes/general/constants.php",
	"CBPTaskStatus" => "classes/general/constants.php",
	"CBPTaskUserStatus" => "classes/general/constants.php",
	"CBPTaskDelegationType" => "classes/general/constants.php",
	"CBPDocument" => "classes/general/document.php",
	"CBPDocumentService" => "classes/general/documentservice.php",
	"CBPArgumentException" => "classes/general/exception.php",
	"CBPArgumentNullException" => "classes/general/exception.php",
	"CBPArgumentOutOfRangeException" => "classes/general/exception.php",
	"CBPArgumentTypeException" => "classes/general/exception.php",
	"CBPInvalidOperationException" => "classes/general/exception.php",
	"CBPNotSupportedException" => "classes/general/exception.php",
	"CBPHelper" => "classes/general/helper.php",
	"CBPAllHistoryService" => "classes/general/historyservice.php",
	"CBPHistoryService" => "classes/general/historyservice.php",
	"CBPHistoryResult" => "classes/general/historyservice.php",
	"CBPRuntime" => "classes/general/runtime.php",
	"CBPRuntimeService" => "classes/general/runtimeservice.php",
	"CBPSchedulerService" => "classes/general/schedulerservice.php",
	"CBPAllStateService" => "classes/general/stateservice.php",
	"CBPStateService" => "classes/general/stateservice.php",
	"CBPAllTaskService" => "classes/general/taskservice.php",
	"CBPTaskService" => "classes/general/taskservice.php",
	"CBPTaskResult" => "classes/general/taskservice.php",
	"CBPAllTrackingService" => "classes/general/trackingservice.php",
	"CBPTrackingService" => "classes/general/trackingservice.php",
	"CBPTrackingType" => "classes/general/trackingservice.php",
	"CBPVirtualDocument" => "classes/general/virtualdocument.php",
	"CBPWorkflow" => "classes/general/workflow.php",
	"CBPAllWorkflowPersister" => "classes/general/workflowpersister.php",
	"CBPWorkflowPersister" => "classes/general/workflowpersister.php",
	"CAllBPWorkflowTemplateLoader" => "classes/general/workflowtemplateloader.php",
	"CBPWorkflowTemplateLoader" => "classes/general/workflowtemplateloader.php",
	"CBPWorkflowTemplateResult" => "classes/general/workflowtemplateloader.php",
	"CBPWorkflowTemplateUser" => "classes/general/workflowtemplateloader.php",
	"CBPWorkflowTemplateValidationException" => "classes/general/workflowtemplateloader.php",
	"CBPCalc" => "classes/general/calc.php",
	"CBPViewHelper" => "classes/general/viewhelper.php",
	'CBPTaskChangedStatus' => "classes/general/constants.php",
	'CBPRestActivity' => 'classes/general/restactivity.php',

	"thurly\\bizproc\\fieldtype" => "lib/fieldtype.php",
	"thurly\\bizproc\\restactivitytable" => "lib/restactivity.php",
	"thurly\\bizproc\\restservice" => "lib/restservice.php",
	"thurly\\bizproc\\workflowinstancetable" => "lib/workflowinstance.php",
	"thurly\\bizproc\\workflowstatetable" => "lib/workflowstate.php",
	"thurly\\bizproc\\workflowtemplatetable" => "lib/workflowtemplate.php",
	"thurly\\bizproc\\basetype\\base" => "lib/basetype/base.php",
	"thurly\\bizproc\\basetype\\booltype" => "lib/basetype/booltype.php",
	"thurly\\bizproc\\basetype\\date" => "lib/basetype/date.php",
	"thurly\\bizproc\\basetype\\datetime" => "lib/basetype/datetime.php",
	"thurly\\bizproc\\basetype\\double" => "lib/basetype/double.php",
	"thurly\\bizproc\\basetype\\file" => "lib/basetype/file.php",
	"thurly\\bizproc\\basetype\\inttype" => "lib/basetype/inttype.php",
	"thurly\\bizproc\\basetype\\select" => "lib/basetype/select.php",
	"thurly\\bizproc\\basetype\\stringtype" => "lib/basetype/stringtype.php",
	"thurly\\bizproc\\basetype\\text" => "lib/basetype/text.php",
	"thurly\\bizproc\\basetype\\user" => "lib/basetype/user.php",
	"thurly\\bizproc\\basetype\\internalselect" => "lib/basetype/internalselect.php",
);
CModule::AddAutoloadClasses("bizproc", $arClasses);
/*patchlimitationmutatormark1*/
include_once($_SERVER["DOCUMENT_ROOT"]."/thurly/modules/bizproc/classes/general/interface.php");

CJSCore::RegisterExt('bp_selector', array(
	'js' => '/thurly/js/bizproc/bp_selector.js',
	'css' => '/thurly/js/bizproc/css/bp_selector.css',
	'lang' => '/thurly/modules/bizproc/lang/'.LANGUAGE_ID.'/install/js/bp_selector.php',
	'rel' => array('core', 'popup', 'translit'),
));

CJSCore::RegisterExt('bp_starter', array(
	'js' => '/thurly/js/bizproc/starter.js',
	//'css' => '/thurly/js/bizproc/css/starter.css',
	'lang' => '/thurly/modules/bizproc/lang/'.LANGUAGE_ID.'/install/js/starter.php',
	'rel' => array('core', 'popup'),
));

CJSCore::RegisterExt('bp_user_selector', array(
	'js' => '/thurly/js/bizproc/user_selector.js',
	//'css' => '/thurly/js/bizproc/css/starter.css',
	//'lang' => '/thurly/modules/bizproc/lang/'.LANGUAGE_ID.'/install/js/starter.php',
	'rel' => array('core', 'popup'),
));